import React from "react";
import Head from "next/head";

export default function HeadComponent() {
  return (
    <Head>
      <title>Pavan Katukala</title>
      <meta name="description" content="Generated by Pavan Katukala" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
